name: Lint Spring Boot Project

on: 
  push: 
    branches: 
      - main  # Trigger on push to the main branch

jobs: 
  lint: 
    runs-on: ubuntu-latest 

    steps: 
      # Step 1: Checkout the code from the repository
      - name: Checkout code 
        uses: actions/checkout@v3 

      # Step 2: Set up JDK 17 for building the project
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: 17 
          distribution: temurin 

      # Step 3: Download Checkstyle JAR
      - name: Download Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -O checkstyle.jar
          # Replace 8.45 with the actual version number you want to use

      # Step 4: Run Checkstyle with the downloaded JAR
      - name: Run Checkstyle
        run: |
          mvn clean checkstyle:checkstyle -Dcheckstyle.config.file=checkstyle.xml

      # Optional: Upload Checkstyle results as an artifact
      - name: Upload Checkstyle results
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
