name: Checkstyle Linting

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  checkstyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest  # You can use any supported OS, ubuntu-latest is commonly used

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (you can modify this based on your Java version)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: temurin 

      # Cache Maven dependencies to speed up future builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven Checkstyle goal to perform code analysis
      - name: Run Checkstyle
        run: mvn checkstyle:check
