name: Lint Spring Boot Project 
on: 
 push: 
    branches: [ main ] 
 
jobs: 
  lint: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: 17 
          distribution: temurin 
      - name: Download Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -O checkstyle.jar
          # Replace 8.45 with the actual version number you want to use

      - name: Run Checkstyle
        run: |
          mvn clean checkstyle:checkstyle -Dcheckstyle.config.file=check
